name: sqfentity
homepage: https://github.com/hhtokpinar/sqfEntity
description: SqfEntity ORM for Flutter/Dart lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework.
repository: https://github.com/hhtokpinar/sqfEntity
version: 2.5.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_sqlcipher: ^3.4.0
  synchronized: 3.3.1
  path: 1.9.1
  sqfentity_gen:
    path: ../sqfentity_gen # remove the first comment mark if you want to debug sqfentity_gen package on your local file system
  sqflite_common: 2.5.5
  sqflite_common_ffi: 2.3.5
  meta: 1.16.0
