name: sqfentity_gen
homepage: https://github.com/hhtokpinar/sqfEntity
description: SqfnEntity Model Generator. SQLite ORM for Flutter lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework. 

version: 2.4.0
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  meta: ^1.7.0
  analyzer: ^6.0.0
  intl: ^0.18.0